config/routes.rb
Rails.application.routes.draw do
  resources :user_mails, only: [:index,:show] do
    get :download_attachment, on: :member
  end

  resources :mail_accounts do
    post :pull_imap, on: :member
  end
  devise_for :users


  mount Crono::Web, at: '/crono'

  match "/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]
  get "logs/:lines" => 'log_view#index', as:'log'

  root to:'mail_accounts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  after_action :verify_authorized, except: :index, unless: :devise_controller?
  after_action :verify_policy_scoped, only: :index, unless: :devise_controller?
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


  def bootstrap_class_for(flash_type)
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

end

app/views/shared/application/_flash_messages.html.slim
- flash.each do |key, value|
  div[class="mx-auto alert #{bootstrap_class_for(key)} alert-dismissible align-center"]
    button type="button" class="close float-right" data-dismiss="alert" aria-label="Close"
      span aria-hidden="true" &times;
    = value

app/views/shared/application/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">
    <%= image_tag asset_path('mailslave.png'),size:'50x50'%>
    MAILSLAVE
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= t(MailAccount,count: 2) %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= content_tag :div, "No Accounts", class:'alert alert-danger dropdown-item' unless current_user.mail_accounts.count > 0 %>
              <%  current_user.mail_accounts.each do |macc| %>
                  <%= link_to macc.login, mail_account_path(macc), class: 'dropdown-item' %>
              <% end %>
              <%= link_to 'New Account', new_mail_account_path(user_id: current_user.id), {class: 'dropdown-item'} %>
            </div>
      <% end %>
      </li>
      <li class="nav-item">
        <%= link_to 'Mails',user_mails_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Logs',log_path(lines: 20), class:'nav-link' %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Search</a>
      </li>
    </ul>
    <%= yield(:search) %>
    <div class="dropdown show navbar-text">
      <a class="dropdown-toggle" href="#" id="ProfileDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fa fa-user-circle-o" aria-hidden="true"></i> <%= user_signed_in? ? current_user.email : 'Guest' %>
      </a>
      <div class="dropdown-menu" aria-labelledby="ProfileDropdown">
        <% if user_signed_in? %>
            <%= link_to "Edit profile", edit_user_registration_path, :class => 'dropdown-item' %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'dropdown-item'  %>
        <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'dropdown-item'  %>
            <%= link_to "Login", new_user_session_path, :class => 'dropdown-item'  %>
        <% end %>
      </div>
    </div>
  </div>
</nav>