config/routes.rb
Rails.application.routes.draw do
  resources :user_mails, only: [:index,:show] do
    get :download_attachment, on: :member
  end

  resources :mail_accounts do
    post :pull_imap, on: :member
  end
  devise_for :users


  mount Crono::Web, at: '/crono'

  match "/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]
  get "logs/:lines" => 'log_view#index', as:'log'

  root to:'mail_accounts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/mail_account.rb
require 'mail'
require 'net/imap'

class MailAccount < ApplicationRecord

  crypt_keeper :login, :password , encryptor: :aes_new, key: 'gotMailSlaveToEncrypt', salt: 'salt'

  belongs_to :user
  has_many :user_mails, :inverse_of => :mail_account
  has_many :mailbox_folders, :dependent => :destroy
  has_many :sync_jobs

  after_create do
    sync!
  end

  has_settings do |setting|
    setting.key :sync_options, defaults: {
      interval: 15, # interval for retrieving TODO: implement
      entry_limit: 25, # process amount of entries, then wait for next sync
      only_seen: true, # only seen messages get archived
      only_older_than: 30, # only archive messages older than X days
      delete_after: 30, # delete messages that are older than x days
      exclude_folders: 'INBOX.Junk,INBOX.Spam',
      archive_folder_name: 'INBOX.mailslave_archive'
    }
  end

  #TODO: clean up old sync jobs?
  def sync_job
    return sync_jobs.last unless sync_jobs.empty?
  end

  def sync!(interval = -1)
    return unless sync_job.nil? || sync_job.complete?
    sjob = sync_jobs.create()
    the_interval = interval == -1 ? settings(:sync_options).interval : interval
    Delayed::Job.enqueue(PullImapJob.new(sjob.id),:run_at => (Time.now + the_interval.minutes).to_datetime )
  end

  def pull_imap
    search_query = ['UNFLAGGED']
    search_query << 'SEEN' if settings(:sync_options).only_seen
    if settings(:sync_options).only_older_than > 0
      search_query << "BEFORE"
      search_query << (Date.today - settings(:sync_options).only_older_than).strftime('%d-%b-%Y')
    end
    mail_sync = MailSync.new(self,settings(:sync_options).entry_limit)
    mail_sync.sync(exclude_folders, search_query)
    mail_sync.disconnect


    #delay(queue: 'sync', run_at: (Time.now + interval.minutes).to_datetime ).pull_imap
  end

  def find_or_create_folder(folder)
    folder_active = settings(:sync_options).exclude_folders.include?(folder)
    acc_folder = mailbox_folders.find_by(name: folder) || mailbox_folders.create(name: folder, sync_active: folder_active)
  end

  def exclude_folders
    return settings(:sync_options).exclude_folders.split(",").map(&:strip) << settings(:sync_options).archive_folder_name
  end

end

app/controllers/mail_accounts_controller.rb
class MailAccountsController < ApplicationController
  before_action :set_mail_account, only: [:show, :edit, :update, :destroy, :pull_imap]
  before_action :authenticate_user!

  # GET /mail_accounts
  # GET /mail_accounts.json
  def index
    @mail_accounts = policy_scope(MailAccount)
  end

  # GET /mail_accounts/1
  # GET /mail_accounts/1.json
  def show
  end

  # GET /mail_accounts/new
  def new
    @mail_account = MailAccount.new
    authorize @mail_account
  end

  # GET /mail_accounts/1/edit
  def edit
  end

  # POST /mail_accounts
  # POST /mail_accounts.json
  def create
    @mail_account = MailAccount.new(mail_account_params)
    authorize(@mail_account)

    respond_to do |format|
      if @mail_account.save
        format.html { redirect_to @mail_account, notice: 'UserMail account was successfully created.' }
        format.json { render :show, status: :created, location: @mail_account }
      else
        format.html { render :new }
        format.json { render json: @mail_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mail_accounts/1
  # PATCH/PUT /mail_accounts/1.json
  def update
    respond_to do |format|
      if @mail_account.update(mail_account_params)
        format.html { redirect_to @mail_account, notice: 'UserMail account was successfully updated.' }
        format.json { render :show, status: :ok, location: @mail_account }
      else
        format.html { render :edit }
        format.json { render json: @mail_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mail_accounts/1
  # DELETE /mail_accounts/1.json
  def destroy
    @mail_account.destroy
    respond_to do |format|
      format.html { redirect_to mail_accounts_url, notice: 'UserMail account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def pull_imap
    authorize(@mail_account)
    #@mail_account.delay(queue:'sync').pull_imap
    @mail_account.sync!(0)
    redirect_to @mail_account
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mail_account
      @mail_account = MailAccount.find(params[:id])
      authorize(@mail_account)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mail_account_params
      params.require(:mail_account).permit(:name, :email, :user_id, :login, :password, :port, :ssl, :host, :smtp_server, :smtp_port)
    end
end

app/helpers/mail_accounts_helper.rb
module MailAccountsHelper
end

app/views/mail_accounts/_form.html.slim
= simple_form_for(@mail_account) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :email
    = f.association :user
    = f.input :login
    = f.input :password
    = f.input :host
    = f.input :port
    = f.input :ssl
    = f.input :smtp_server
    = f.input :smtp_port

  .form-actions
    = f.button :submit

app/views/mail_accounts/edit.html.slim
h1 Editing mail_account

== render 'form'

= link_to 'Show', @mail_account
'  |
= link_to 'Back', mail_accounts_path

app/views/mail_accounts/index.html.slim
h1 Listing mail_accounts

table
  thead
    tr
      th Name
      th Email
      th User
      th Login
      th Port
      th Ssl
      th Host
      th
      th
      th

  tbody
    - @mail_accounts.each do |mail_account|
      tr
        td = mail_account.name
        td = mail_account.email
        td = mail_account.user
        td = mail_account.login
        td = mail_account.port
        td = mail_account.ssl
        td = mail_account.host
        td = link_to 'Show', mail_account
        td = link_to 'Edit', edit_mail_account_path(mail_account)
        td = link_to 'Destroy', mail_account, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New UserMail account', new_mail_account_path

app/views/mail_accounts/new.html.slim
h1 New mail_account

== render 'form'

= link_to 'Back', mail_accounts_path

app/views/mail_accounts/show.html.slim
p#notice = notice

h2
  = fa_icon 'user-circle-o'
  = @mail_account.name
  span.text-muted.m-4
    = fa_icon 'envelope-o'
    = @mail_account.email



div.row
  div.col-md-6
    table
      thead

      tbody
        tr
          td
            strong = t(:login)
          td = @mail_account.login
        tr
          td
            strong = t(:host)
          td = "#{@mail_account.host}:#{@mail_account.port}"
        tr
          td
            strong SSL
          td = @mail_account.ssl? ? fa_icon('check') : fa_icon('times')
  div.col-md-6
    table
      thead

      tbody
        tr
          td
            strong interval
          td = @mail_account.settings(:sync_options).interval
        tr
          td
            strong only_seen
          td = @mail_account.settings(:sync_options).only_seen ? fa_icon('check') : fa_icon('times')
        tr
          td
            strong only_older_than
          td = " #{@mail_account.settings(:sync_options).only_older_than} days"
        tr
          td
            strong delete_after
          td = " #{@mail_account.settings(:sync_options).delete_after} days"
        tr
          td
            strong exclude_folders
          td = @mail_account.settings(:sync_options).exclude_folders
  div.col-md-6
    strong Last sync:
    - if @mail_account.sync_job
      - job = @mail_account.sync_job
      = "#{l job.sync_start} (p:#{job.processed_entries} n:#{job.new_entries} s:#{job.skipped_entries}) -- #{job.state}" unless @mail_account.sync_job.nil?
      br
      button.btn.btn-primary.mb-2 data-toggle="collapse" href="#sync-info" role="button" aria-expanded="false" aria-controls="sync-info"
        | Show
      div#sync-info.collapse
        = "job ##{job.id}"
        pre
          = job.info
          hr
          = "#{l job.sync_start} until #{l job.sync_end}"
    - else
      | No sync jobs
hr

div.row
  div.col-md-2
    ul.list-group
      - @mail_account.mailbox_folders.each do |f|
        li.list-group-item title="#{f.name}"
          = f.name
  div.col
    h2 Mails (#{@mail_account.user_mails.count})
    = link_to "Fetch user_mails", pull_imap_mail_account_path(id: @mail_account), :method => :post
    - @mails = @mail_account.user_mails.paginate(:page => params[:page], :per_page => 15)

    table.table-striped
      thead.thead-inverse
        tr
          th From
          th Received
          th Subject
          th
      tbody
        - @mails.each do |mail|
          tr
            td
              = mail.from
            td
              = mail.receive_date
            td
              = mail.subject
            td
              = link_to 'Show',user_mail_path(id: mail.id)
    = will_paginate @mails
= link_to 'Edit', edit_mail_account_path(@mail_account)
'  |
= link_to 'Back', mail_accounts_path